namespace Zendeta
{
    partial class FormAddPatient
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormAddPatient));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.tb_name = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_email = new Bunifu.UI.WinForms.BunifuTextBox();
            this.rb_male = new Bunifu.UI.WinForms.BunifuRadioButton();
            this.rb_female = new Bunifu.UI.WinForms.BunifuRadioButton();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.dp_birthday = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.tb_phone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel10 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tb_postal = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_city = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tb_address = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btn_save = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuButton23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // tb_name
            // 
            this.tb_name.AcceptsReturn = false;
            this.tb_name.AcceptsTab = false;
            this.tb_name.AnimationSpeed = 200;
            this.tb_name.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_name.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_name.AutoSizeHeight = true;
            this.tb_name.BackColor = System.Drawing.Color.Transparent;
            this.tb_name.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_name.BackgroundImage")));
            this.tb_name.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_name.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_name.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_name.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_name.BorderRadius = 1;
            this.tb_name.BorderThickness = 1;
            this.tb_name.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_name.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_name.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_name.DefaultText = "";
            this.tb_name.FillColor = System.Drawing.Color.White;
            this.tb_name.HideSelection = true;
            this.tb_name.IconLeft = null;
            this.tb_name.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_name.IconPadding = 10;
            this.tb_name.IconRight = null;
            this.tb_name.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_name.Lines = new string[0];
            this.tb_name.Location = new System.Drawing.Point(88, 107);
            this.tb_name.MaxLength = 32767;
            this.tb_name.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_name.Modified = false;
            this.tb_name.Multiline = false;
            this.tb_name.Name = "tb_name";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_name.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_name.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_name.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_name.OnIdleState = stateProperties4;
            this.tb_name.Padding = new System.Windows.Forms.Padding(3);
            this.tb_name.PasswordChar = '\0';
            this.tb_name.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_name.PlaceholderText = "Name";
            this.tb_name.ReadOnly = false;
            this.tb_name.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_name.SelectedText = "";
            this.tb_name.SelectionLength = 0;
            this.tb_name.SelectionStart = 0;
            this.tb_name.ShortcutsEnabled = true;
            this.tb_name.Size = new System.Drawing.Size(246, 32);
            this.tb_name.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_name.TabIndex = 0;
            this.tb_name.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_name.TextMarginBottom = 0;
            this.tb_name.TextMarginLeft = 3;
            this.tb_name.TextMarginTop = 1;
            this.tb_name.TextPlaceholder = "Name";
            this.tb_name.UseSystemPasswordChar = false;
            this.tb_name.WordWrap = true;
            // 
            // tb_email
            // 
            this.tb_email.AcceptsReturn = false;
            this.tb_email.AcceptsTab = false;
            this.tb_email.AnimationSpeed = 200;
            this.tb_email.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_email.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_email.AutoSizeHeight = true;
            this.tb_email.BackColor = System.Drawing.Color.Transparent;
            this.tb_email.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_email.BackgroundImage")));
            this.tb_email.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_email.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_email.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_email.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_email.BorderRadius = 1;
            this.tb_email.BorderThickness = 1;
            this.tb_email.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_email.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_email.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_email.DefaultText = "";
            this.tb_email.FillColor = System.Drawing.Color.White;
            this.tb_email.HideSelection = true;
            this.tb_email.IconLeft = null;
            this.tb_email.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_email.IconPadding = 10;
            this.tb_email.IconRight = null;
            this.tb_email.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_email.Lines = new string[0];
            this.tb_email.Location = new System.Drawing.Point(88, 145);
            this.tb_email.MaxLength = 32767;
            this.tb_email.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_email.Modified = false;
            this.tb_email.Multiline = false;
            this.tb_email.Name = "tb_email";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_email.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_email.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_email.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_email.OnIdleState = stateProperties8;
            this.tb_email.Padding = new System.Windows.Forms.Padding(3);
            this.tb_email.PasswordChar = '\0';
            this.tb_email.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_email.PlaceholderText = "Email";
            this.tb_email.ReadOnly = false;
            this.tb_email.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_email.SelectedText = "";
            this.tb_email.SelectionLength = 0;
            this.tb_email.SelectionStart = 0;
            this.tb_email.ShortcutsEnabled = true;
            this.tb_email.Size = new System.Drawing.Size(246, 32);
            this.tb_email.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_email.TabIndex = 1;
            this.tb_email.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_email.TextMarginBottom = 0;
            this.tb_email.TextMarginLeft = 3;
            this.tb_email.TextMarginTop = 1;
            this.tb_email.TextPlaceholder = "Email";
            this.tb_email.UseSystemPasswordChar = false;
            this.tb_email.WordWrap = true;
            // 
            // rb_male
            // 
            this.rb_male.AllowBindingControlLocation = false;
            this.rb_male.BackColor = System.Drawing.Color.Transparent;
            this.rb_male.BindingControlPosition = Bunifu.UI.WinForms.BunifuRadioButton.BindingControlPositions.Right;
            this.rb_male.BorderThickness = 1;
            this.rb_male.Checked = true;
            this.rb_male.Location = new System.Drawing.Point(88, 221);
            this.rb_male.Name = "rb_male";
            this.rb_male.OutlineColor = System.Drawing.Color.DodgerBlue;
            this.rb_male.OutlineColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.rb_male.OutlineColorUnchecked = System.Drawing.Color.DarkGray;
            this.rb_male.RadioColor = System.Drawing.Color.DodgerBlue;
            this.rb_male.RadioColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.rb_male.Size = new System.Drawing.Size(21, 21);
            this.rb_male.TabIndex = 2;
            this.rb_male.Text = null;
            this.rb_male.CheckedChanged2 += new System.EventHandler<Bunifu.UI.WinForms.BunifuRadioButton.CheckedChangedEventArgs>(this.bunifuRadioButton1_CheckedChanged2);
            // 
            // rb_female
            // 
            this.rb_female.AllowBindingControlLocation = false;
            this.rb_female.BackColor = System.Drawing.Color.Transparent;
            this.rb_female.BindingControlPosition = Bunifu.UI.WinForms.BunifuRadioButton.BindingControlPositions.Right;
            this.rb_female.BorderThickness = 1;
            this.rb_female.Checked = false;
            this.rb_female.Location = new System.Drawing.Point(204, 221);
            this.rb_female.Name = "rb_female";
            this.rb_female.OutlineColor = System.Drawing.Color.DodgerBlue;
            this.rb_female.OutlineColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.rb_female.OutlineColorUnchecked = System.Drawing.Color.DarkGray;
            this.rb_female.RadioColor = System.Drawing.Color.DodgerBlue;
            this.rb_female.RadioColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.rb_female.Size = new System.Drawing.Size(21, 21);
            this.rb_female.TabIndex = 3;
            this.rb_female.Text = null;
            this.rb_female.CheckedChanged2 += new System.EventHandler<Bunifu.UI.WinForms.BunifuRadioButton.CheckedChangedEventArgs>(this.bunifuRadioButton2_CheckedChanged2);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.Location = new System.Drawing.Point(115, 224);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(26, 15);
            this.bunifuLabel1.TabIndex = 4;
            this.bunifuLabel1.Text = "Male";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel1.Click += new System.EventHandler(this.bunifuLabel1_Click);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.Location = new System.Drawing.Point(231, 224);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(38, 15);
            this.bunifuLabel2.TabIndex = 5;
            this.bunifuLabel2.Text = "Female";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel2.Click += new System.EventHandler(this.bunifuLabel2_Click);
            // 
            // dp_birthday
            // 
            this.dp_birthday.BackColor = System.Drawing.Color.Transparent;
            this.dp_birthday.BorderColor = System.Drawing.Color.Silver;
            this.dp_birthday.BorderRadius = 1;
            this.dp_birthday.Color = System.Drawing.Color.Silver;
            this.dp_birthday.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dp_birthday.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dp_birthday.DisabledColor = System.Drawing.Color.Gray;
            this.dp_birthday.DisplayWeekNumbers = false;
            this.dp_birthday.DPHeight = 0;
            this.dp_birthday.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dp_birthday.FillDatePicker = false;
            this.dp_birthday.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dp_birthday.ForeColor = System.Drawing.Color.Black;
            this.dp_birthday.Icon = ((System.Drawing.Image)(resources.GetObject("dp_birthday.Icon")));
            this.dp_birthday.IconColor = System.Drawing.Color.Gray;
            this.dp_birthday.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dp_birthday.LeftTextMargin = 5;
            this.dp_birthday.Location = new System.Drawing.Point(88, 248);
            this.dp_birthday.MinimumSize = new System.Drawing.Size(4, 32);
            this.dp_birthday.Name = "dp_birthday";
            this.dp_birthday.Size = new System.Drawing.Size(246, 32);
            this.dp_birthday.TabIndex = 6;
            this.dp_birthday.ValueChanged += new System.EventHandler(this.bunifuDatePicker1_ValueChanged);
            // 
            // tb_phone
            // 
            this.tb_phone.AcceptsReturn = false;
            this.tb_phone.AcceptsTab = false;
            this.tb_phone.AnimationSpeed = 200;
            this.tb_phone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_phone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_phone.AutoSizeHeight = true;
            this.tb_phone.BackColor = System.Drawing.Color.Transparent;
            this.tb_phone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_phone.BackgroundImage")));
            this.tb_phone.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_phone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_phone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_phone.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_phone.BorderRadius = 1;
            this.tb_phone.BorderThickness = 1;
            this.tb_phone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_phone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_phone.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_phone.DefaultText = "";
            this.tb_phone.FillColor = System.Drawing.Color.White;
            this.tb_phone.HideSelection = true;
            this.tb_phone.IconLeft = null;
            this.tb_phone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_phone.IconPadding = 10;
            this.tb_phone.IconRight = null;
            this.tb_phone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_phone.Lines = new string[0];
            this.tb_phone.Location = new System.Drawing.Point(88, 183);
            this.tb_phone.MaxLength = 32767;
            this.tb_phone.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_phone.Modified = false;
            this.tb_phone.Multiline = false;
            this.tb_phone.Name = "tb_phone";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_phone.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_phone.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_phone.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_phone.OnIdleState = stateProperties12;
            this.tb_phone.Padding = new System.Windows.Forms.Padding(3);
            this.tb_phone.PasswordChar = '\0';
            this.tb_phone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_phone.PlaceholderText = "Phone";
            this.tb_phone.ReadOnly = false;
            this.tb_phone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_phone.SelectedText = "";
            this.tb_phone.SelectionLength = 0;
            this.tb_phone.SelectionStart = 0;
            this.tb_phone.ShortcutsEnabled = true;
            this.tb_phone.Size = new System.Drawing.Size(246, 32);
            this.tb_phone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_phone.TabIndex = 7;
            this.tb_phone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_phone.TextMarginBottom = 0;
            this.tb_phone.TextMarginLeft = 3;
            this.tb_phone.TextMarginTop = 1;
            this.tb_phone.TextPlaceholder = "Phone";
            this.tb_phone.UseSystemPasswordChar = false;
            this.tb_phone.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(36, 116);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(32, 15);
            this.bunifuLabel3.TabIndex = 8;
            this.bunifuLabel3.Text = "Name";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel3.Click += new System.EventHandler(this.bunifuLabel3_Click);
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel4.Location = new System.Drawing.Point(39, 154);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(29, 15);
            this.bunifuLabel4.TabIndex = 9;
            this.bunifuLabel4.Text = "Email";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel4.Click += new System.EventHandler(this.bunifuLabel4_Click);
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel5.Location = new System.Drawing.Point(34, 192);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(34, 15);
            this.bunifuLabel5.TabIndex = 10;
            this.bunifuLabel5.Text = "Phone";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel5.Click += new System.EventHandler(this.bunifuLabel5_Click);
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel6.Location = new System.Drawing.Point(30, 221);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(38, 15);
            this.bunifuLabel6.TabIndex = 11;
            this.bunifuLabel6.Text = "Gender";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel7.Location = new System.Drawing.Point(19, 256);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(49, 15);
            this.bunifuLabel7.TabIndex = 12;
            this.bunifuLabel7.Text = "BirthDate";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel7.Click += new System.EventHandler(this.bunifuLabel7_Click);
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel8.Location = new System.Drawing.Point(362, 193);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(63, 15);
            this.bunifuLabel8.TabIndex = 18;
            this.bunifuLabel8.Text = "Postal Code";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.CursorType = null;
            this.bunifuLabel9.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel9.Location = new System.Drawing.Point(367, 155);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(21, 15);
            this.bunifuLabel9.TabIndex = 17;
            this.bunifuLabel9.Text = "City";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel10
            // 
            this.bunifuLabel10.AllowParentOverrides = false;
            this.bunifuLabel10.AutoEllipsis = false;
            this.bunifuLabel10.CursorType = null;
            this.bunifuLabel10.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel10.Location = new System.Drawing.Point(367, 117);
            this.bunifuLabel10.Name = "bunifuLabel10";
            this.bunifuLabel10.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel10.Size = new System.Drawing.Size(42, 15);
            this.bunifuLabel10.TabIndex = 16;
            this.bunifuLabel10.Text = "Address";
            this.bunifuLabel10.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel10.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tb_postal
            // 
            this.tb_postal.AcceptsReturn = false;
            this.tb_postal.AcceptsTab = false;
            this.tb_postal.AnimationSpeed = 200;
            this.tb_postal.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_postal.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_postal.AutoSizeHeight = true;
            this.tb_postal.BackColor = System.Drawing.Color.Transparent;
            this.tb_postal.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_postal.BackgroundImage")));
            this.tb_postal.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_postal.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_postal.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_postal.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_postal.BorderRadius = 1;
            this.tb_postal.BorderThickness = 1;
            this.tb_postal.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_postal.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_postal.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_postal.DefaultText = "";
            this.tb_postal.FillColor = System.Drawing.Color.White;
            this.tb_postal.HideSelection = true;
            this.tb_postal.IconLeft = null;
            this.tb_postal.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_postal.IconPadding = 10;
            this.tb_postal.IconRight = null;
            this.tb_postal.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_postal.Lines = new string[0];
            this.tb_postal.Location = new System.Drawing.Point(431, 184);
            this.tb_postal.MaxLength = 32767;
            this.tb_postal.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_postal.Modified = false;
            this.tb_postal.Multiline = false;
            this.tb_postal.Name = "tb_postal";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_postal.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_postal.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_postal.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_postal.OnIdleState = stateProperties16;
            this.tb_postal.Padding = new System.Windows.Forms.Padding(3);
            this.tb_postal.PasswordChar = '\0';
            this.tb_postal.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_postal.PlaceholderText = "Postal Code";
            this.tb_postal.ReadOnly = false;
            this.tb_postal.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_postal.SelectedText = "";
            this.tb_postal.SelectionLength = 0;
            this.tb_postal.SelectionStart = 0;
            this.tb_postal.ShortcutsEnabled = true;
            this.tb_postal.Size = new System.Drawing.Size(246, 32);
            this.tb_postal.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_postal.TabIndex = 15;
            this.tb_postal.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_postal.TextMarginBottom = 0;
            this.tb_postal.TextMarginLeft = 3;
            this.tb_postal.TextMarginTop = 1;
            this.tb_postal.TextPlaceholder = "Postal Code";
            this.tb_postal.UseSystemPasswordChar = false;
            this.tb_postal.WordWrap = true;
            // 
            // tb_city
            // 
            this.tb_city.AcceptsReturn = false;
            this.tb_city.AcceptsTab = false;
            this.tb_city.AnimationSpeed = 200;
            this.tb_city.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_city.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_city.AutoSizeHeight = true;
            this.tb_city.BackColor = System.Drawing.Color.Transparent;
            this.tb_city.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_city.BackgroundImage")));
            this.tb_city.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_city.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_city.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_city.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_city.BorderRadius = 1;
            this.tb_city.BorderThickness = 1;
            this.tb_city.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_city.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_city.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_city.DefaultText = "";
            this.tb_city.FillColor = System.Drawing.Color.White;
            this.tb_city.HideSelection = true;
            this.tb_city.IconLeft = null;
            this.tb_city.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_city.IconPadding = 10;
            this.tb_city.IconRight = null;
            this.tb_city.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_city.Lines = new string[0];
            this.tb_city.Location = new System.Drawing.Point(431, 146);
            this.tb_city.MaxLength = 32767;
            this.tb_city.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_city.Modified = false;
            this.tb_city.Multiline = false;
            this.tb_city.Name = "tb_city";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_city.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_city.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_city.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_city.OnIdleState = stateProperties20;
            this.tb_city.Padding = new System.Windows.Forms.Padding(3);
            this.tb_city.PasswordChar = '\0';
            this.tb_city.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_city.PlaceholderText = "City";
            this.tb_city.ReadOnly = false;
            this.tb_city.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_city.SelectedText = "";
            this.tb_city.SelectionLength = 0;
            this.tb_city.SelectionStart = 0;
            this.tb_city.ShortcutsEnabled = true;
            this.tb_city.Size = new System.Drawing.Size(246, 32);
            this.tb_city.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_city.TabIndex = 14;
            this.tb_city.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_city.TextMarginBottom = 0;
            this.tb_city.TextMarginLeft = 3;
            this.tb_city.TextMarginTop = 1;
            this.tb_city.TextPlaceholder = "City";
            this.tb_city.UseSystemPasswordChar = false;
            this.tb_city.WordWrap = true;
            // 
            // tb_address
            // 
            this.tb_address.AcceptsReturn = false;
            this.tb_address.AcceptsTab = false;
            this.tb_address.AnimationSpeed = 200;
            this.tb_address.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tb_address.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tb_address.AutoSizeHeight = true;
            this.tb_address.BackColor = System.Drawing.Color.Transparent;
            this.tb_address.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tb_address.BackgroundImage")));
            this.tb_address.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tb_address.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tb_address.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tb_address.BorderColorIdle = System.Drawing.Color.Silver;
            this.tb_address.BorderRadius = 1;
            this.tb_address.BorderThickness = 1;
            this.tb_address.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tb_address.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_address.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tb_address.DefaultText = "";
            this.tb_address.FillColor = System.Drawing.Color.White;
            this.tb_address.HideSelection = true;
            this.tb_address.IconLeft = null;
            this.tb_address.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_address.IconPadding = 10;
            this.tb_address.IconRight = null;
            this.tb_address.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tb_address.Lines = new string[0];
            this.tb_address.Location = new System.Drawing.Point(431, 108);
            this.tb_address.MaxLength = 32767;
            this.tb_address.MinimumSize = new System.Drawing.Size(1, 1);
            this.tb_address.Modified = false;
            this.tb_address.Multiline = false;
            this.tb_address.Name = "tb_address";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_address.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tb_address.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_address.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tb_address.OnIdleState = stateProperties24;
            this.tb_address.Padding = new System.Windows.Forms.Padding(3);
            this.tb_address.PasswordChar = '\0';
            this.tb_address.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tb_address.PlaceholderText = "Street Address";
            this.tb_address.ReadOnly = false;
            this.tb_address.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tb_address.SelectedText = "";
            this.tb_address.SelectionLength = 0;
            this.tb_address.SelectionStart = 0;
            this.tb_address.ShortcutsEnabled = true;
            this.tb_address.Size = new System.Drawing.Size(246, 32);
            this.tb_address.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tb_address.TabIndex = 13;
            this.tb_address.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tb_address.TextMarginBottom = 0;
            this.tb_address.TextMarginLeft = 3;
            this.tb_address.TextMarginTop = 1;
            this.tb_address.TextPlaceholder = "Street Address";
            this.tb_address.UseSystemPasswordChar = false;
            this.tb_address.WordWrap = true;
            // 
            // btn_save
            // 
            this.btn_save.AllowAnimations = true;
            this.btn_save.AllowMouseEffects = true;
            this.btn_save.AllowToggling = false;
            this.btn_save.AnimationSpeed = 200;
            this.btn_save.AutoGenerateColors = false;
            this.btn_save.AutoRoundBorders = false;
            this.btn_save.AutoSizeLeftIcon = true;
            this.btn_save.AutoSizeRightIcon = true;
            this.btn_save.BackColor = System.Drawing.Color.Transparent;
            this.btn_save.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btn_save.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_save.BackgroundImage")));
            this.btn_save.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_save.ButtonText = "Save";
            this.btn_save.ButtonTextMarginLeft = 0;
            this.btn_save.ColorContrastOnClick = 45;
            this.btn_save.ColorContrastOnHover = 45;
            this.btn_save.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_save.CustomizableEdges = borderEdges1;
            this.btn_save.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_save.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_save.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_save.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_save.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn_save.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btn_save.ForeColor = System.Drawing.Color.White;
            this.btn_save.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_save.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_save.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_save.IconMarginLeft = 11;
            this.btn_save.IconPadding = 10;
            this.btn_save.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_save.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_save.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_save.IconSize = 25;
            this.btn_save.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_save.IdleBorderRadius = 1;
            this.btn_save.IdleBorderThickness = 1;
            this.btn_save.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btn_save.IdleIconLeftImage = null;
            this.btn_save.IdleIconRightImage = null;
            this.btn_save.IndicateFocus = false;
            this.btn_save.Location = new System.Drawing.Point(588, 249);
            this.btn_save.Name = "btn_save";
            this.btn_save.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_save.OnDisabledState.BorderRadius = 1;
            this.btn_save.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_save.OnDisabledState.BorderThickness = 1;
            this.btn_save.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_save.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_save.OnDisabledState.IconLeftImage = null;
            this.btn_save.OnDisabledState.IconRightImage = null;
            this.btn_save.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_save.onHoverState.BorderRadius = 1;
            this.btn_save.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_save.onHoverState.BorderThickness = 1;
            this.btn_save.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_save.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_save.onHoverState.IconLeftImage = null;
            this.btn_save.onHoverState.IconRightImage = null;
            this.btn_save.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btn_save.OnIdleState.BorderRadius = 1;
            this.btn_save.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_save.OnIdleState.BorderThickness = 1;
            this.btn_save.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btn_save.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btn_save.OnIdleState.IconLeftImage = null;
            this.btn_save.OnIdleState.IconRightImage = null;
            this.btn_save.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_save.OnPressedState.BorderRadius = 1;
            this.btn_save.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn_save.OnPressedState.BorderThickness = 1;
            this.btn_save.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_save.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_save.OnPressedState.IconLeftImage = null;
            this.btn_save.OnPressedState.IconRightImage = null;
            this.btn_save.Size = new System.Drawing.Size(89, 31);
            this.btn_save.TabIndex = 19;
            this.btn_save.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_save.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_save.TextMarginLeft = 0;
            this.btn_save.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_save.UseDefaultRadiusAndThickness = true;
            this.btn_save.Click += new System.EventHandler(this.btn_save_Click);
            // 
            // bunifuButton22
            // 
            this.bunifuButton22.AllowAnimations = true;
            this.bunifuButton22.AllowMouseEffects = true;
            this.bunifuButton22.AllowToggling = false;
            this.bunifuButton22.AnimationSpeed = 200;
            this.bunifuButton22.AutoGenerateColors = false;
            this.bunifuButton22.AutoRoundBorders = false;
            this.bunifuButton22.AutoSizeLeftIcon = true;
            this.bunifuButton22.AutoSizeRightIcon = true;
            this.bunifuButton22.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton22.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton22.BackgroundImage")));
            this.bunifuButton22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.ButtonText = "Cancel";
            this.bunifuButton22.ButtonTextMarginLeft = 0;
            this.bunifuButton22.ColorContrastOnClick = 45;
            this.bunifuButton22.ColorContrastOnHover = 45;
            this.bunifuButton22.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton22.CustomizableEdges = borderEdges2;
            this.bunifuButton22.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton22.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton22.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton22.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton22.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton22.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton22.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton22.IconMarginLeft = 11;
            this.bunifuButton22.IconPadding = 10;
            this.bunifuButton22.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton22.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton22.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton22.IconSize = 25;
            this.bunifuButton22.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton22.IdleBorderRadius = 1;
            this.bunifuButton22.IdleBorderThickness = 1;
            this.bunifuButton22.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.IdleIconLeftImage = null;
            this.bunifuButton22.IdleIconRightImage = null;
            this.bunifuButton22.IndicateFocus = false;
            this.bunifuButton22.Location = new System.Drawing.Point(493, 249);
            this.bunifuButton22.Name = "bunifuButton22";
            this.bunifuButton22.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.OnDisabledState.BorderRadius = 1;
            this.bunifuButton22.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnDisabledState.BorderThickness = 1;
            this.bunifuButton22.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.OnDisabledState.IconLeftImage = null;
            this.bunifuButton22.OnDisabledState.IconRightImage = null;
            this.bunifuButton22.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton22.onHoverState.BorderRadius = 1;
            this.bunifuButton22.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.onHoverState.BorderThickness = 1;
            this.bunifuButton22.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton22.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.onHoverState.IconLeftImage = null;
            this.bunifuButton22.onHoverState.IconRightImage = null;
            this.bunifuButton22.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton22.OnIdleState.BorderRadius = 1;
            this.bunifuButton22.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnIdleState.BorderThickness = 1;
            this.bunifuButton22.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.OnIdleState.ForeColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton22.OnIdleState.IconLeftImage = null;
            this.bunifuButton22.OnIdleState.IconRightImage = null;
            this.bunifuButton22.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton22.OnPressedState.BorderRadius = 1;
            this.bunifuButton22.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnPressedState.BorderThickness = 1;
            this.bunifuButton22.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton22.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.OnPressedState.IconLeftImage = null;
            this.bunifuButton22.OnPressedState.IconRightImage = null;
            this.bunifuButton22.Size = new System.Drawing.Size(89, 31);
            this.bunifuButton22.TabIndex = 20;
            this.bunifuButton22.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton22.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton22.TextMarginLeft = 0;
            this.bunifuButton22.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton22.UseDefaultRadiusAndThickness = true;
            this.bunifuButton22.Click += new System.EventHandler(this.bunifuButton22_Click);
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 45;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(88, 0);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(91, 91);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 21;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuButton23
            // 
            this.bunifuButton23.AllowAnimations = true;
            this.bunifuButton23.AllowMouseEffects = true;
            this.bunifuButton23.AllowToggling = false;
            this.bunifuButton23.AnimationSpeed = 200;
            this.bunifuButton23.AutoGenerateColors = false;
            this.bunifuButton23.AutoRoundBorders = false;
            this.bunifuButton23.AutoSizeLeftIcon = true;
            this.bunifuButton23.AutoSizeRightIcon = true;
            this.bunifuButton23.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton23.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButton23.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton23.BackgroundImage")));
            this.bunifuButton23.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.ButtonText = "Pick Image";
            this.bunifuButton23.ButtonTextMarginLeft = 0;
            this.bunifuButton23.ColorContrastOnClick = 45;
            this.bunifuButton23.ColorContrastOnHover = 45;
            this.bunifuButton23.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton23.CustomizableEdges = borderEdges3;
            this.bunifuButton23.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton23.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton23.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton23.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton23.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton23.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton23.ForeColor = System.Drawing.Color.White;
            this.bunifuButton23.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton23.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton23.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton23.IconMarginLeft = 11;
            this.bunifuButton23.IconPadding = 10;
            this.bunifuButton23.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton23.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton23.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton23.IconSize = 25;
            this.bunifuButton23.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton23.IdleBorderRadius = 1;
            this.bunifuButton23.IdleBorderThickness = 1;
            this.bunifuButton23.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton23.IdleIconLeftImage = null;
            this.bunifuButton23.IdleIconRightImage = null;
            this.bunifuButton23.IndicateFocus = false;
            this.bunifuButton23.Location = new System.Drawing.Point(197, 73);
            this.bunifuButton23.Name = "bunifuButton23";
            this.bunifuButton23.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton23.OnDisabledState.BorderRadius = 1;
            this.bunifuButton23.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.OnDisabledState.BorderThickness = 1;
            this.bunifuButton23.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton23.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton23.OnDisabledState.IconLeftImage = null;
            this.bunifuButton23.OnDisabledState.IconRightImage = null;
            this.bunifuButton23.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton23.onHoverState.BorderRadius = 1;
            this.bunifuButton23.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.onHoverState.BorderThickness = 1;
            this.bunifuButton23.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton23.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton23.onHoverState.IconLeftImage = null;
            this.bunifuButton23.onHoverState.IconRightImage = null;
            this.bunifuButton23.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton23.OnIdleState.BorderRadius = 1;
            this.bunifuButton23.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.OnIdleState.BorderThickness = 1;
            this.bunifuButton23.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton23.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton23.OnIdleState.IconLeftImage = null;
            this.bunifuButton23.OnIdleState.IconRightImage = null;
            this.bunifuButton23.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton23.OnPressedState.BorderRadius = 1;
            this.bunifuButton23.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.OnPressedState.BorderThickness = 1;
            this.bunifuButton23.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton23.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton23.OnPressedState.IconLeftImage = null;
            this.bunifuButton23.OnPressedState.IconRightImage = null;
            this.bunifuButton23.Size = new System.Drawing.Size(83, 18);
            this.bunifuButton23.TabIndex = 22;
            this.bunifuButton23.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton23.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton23.TextMarginLeft = 0;
            this.bunifuButton23.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton23.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Location = new System.Drawing.Point(13, 97);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(332, 194);
            this.bunifuPanel1.TabIndex = 23;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Location = new System.Drawing.Point(362, 97);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(315, 145);
            this.bunifuPanel2.TabIndex = 24;
            // 
            // FormAddPatient
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.AliceBlue;
            this.ClientSize = new System.Drawing.Size(689, 303);
            this.Controls.Add(this.bunifuButton23);
            this.Controls.Add(this.bunifuPictureBox1);
            this.Controls.Add(this.bunifuButton22);
            this.Controls.Add(this.btn_save);
            this.Controls.Add(this.bunifuLabel8);
            this.Controls.Add(this.bunifuLabel9);
            this.Controls.Add(this.bunifuLabel10);
            this.Controls.Add(this.tb_postal);
            this.Controls.Add(this.tb_city);
            this.Controls.Add(this.tb_address);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.tb_phone);
            this.Controls.Add(this.dp_birthday);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.rb_female);
            this.Controls.Add(this.rb_male);
            this.Controls.Add(this.tb_email);
            this.Controls.Add(this.tb_name);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.bunifuPanel2);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormAddPatient";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FormAddPatient";
            this.Load += new System.EventHandler(this.FormAddPatient_Load);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox tb_name;
        private Bunifu.UI.WinForms.BunifuTextBox tb_email;
        private Bunifu.UI.WinForms.BunifuRadioButton rb_male;
        private Bunifu.UI.WinForms.BunifuRadioButton rb_female;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuDatePicker dp_birthday;
        private Bunifu.UI.WinForms.BunifuTextBox tb_phone;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel10;
        private Bunifu.UI.WinForms.BunifuTextBox tb_postal;
        private Bunifu.UI.WinForms.BunifuTextBox tb_city;
        private Bunifu.UI.WinForms.BunifuTextBox tb_address;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn_save;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton22;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton23;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
    }
}